@echo off
echo ============================================
echo    AI Tools Navigation
echo ============================================
echo.

tasklist /fi "imagename eq node.exe" 2>nul | find /i "node" >nul 2>&1
if errorlevel 1 (
    echo [!] Node not running, starting...
    cd /d "C:\Users\83718\.qclaw\workspace\ai-navigation\server"
    start "" /min node server.js
    timeout /t 3 /nobreak >nul
)

tasklist /fi "imagename eq cpolar.exe" 2>nul | find /i "cpolar" >nul 2>&1
if errorlevel 1 (
    echo [!] Cpolar not running, starting...
    start "" /min "C:\Program Files\cpolar\cpolar.exe" http 3000
    echo [!] Waiting for tunnel...
    timeout /t 10 /nobreak >nul
)

echo [Fetching live URL...]
powershell -NoProfile -EncodedCommand dAByAHkAewAkAHIAPQBJAG4AdgBvAGsAZQAtAFIAZQBzAHQATQBlAHQAaABvAGQAIABoAHQAdABwADoALwAvADEAMgA3AC4AMAAuADAALgAxADoANAAwADQAMgAvAGEAcABpAC8AdgAxAC8AdAB1AG4AbgBlAGwAcwAgAC0AVABpAG0AZQBvAHUAdABTAGUAYwAgADUAOwAkAHQAPQAkAHIALgBkAGEAdABhAC4AdAB1AG4AbgBlAGwAcwB8AFcAaABlAHIAZQAtAE8AYgBqAGUAYwB0AHsAJABfAC4AcAB1AGIAbABpAGMAXwB1AHIAbAAgAC0AbQBhAHQAYwBoACAAJwBoAHQAdABwAHMAJwB9AHwAUwBlAGwAZQBjAHQALQBPAGIAagBlAGMAdAAgAC0ARgBpAHIAcwB0ACAAMQA7AGkAZgAoACQAdAApAHsAVwByAGkAdABlAC0ASABvAHMAdAAgACcAJwA7AFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnAD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQAnADsAVwByAGkAdABlAC0ASABvAHMAdAAgACcAIAAgAEYAcgBvAG4AdABlAG4AZAA6ACAAJwAkAHQALgBwAHUAYgBsAGkAYwBfAHUAcgBsADsAVwByAGkAdABlAC0ASABvAHMAdAAgACcAIAAgAEEAZABtAGkAbgA6ACAAIAAgACAAJwAkAHQALgBwAHUAYgBsAGkAYwBfAHUAcgBsACcALwBhAGQAbQBpAG4AJwA7AFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnACAAIABQAGEAcwBzAHcAbwByAGQAOgAgAGEAZABtAGkAbgAxADIAMwAnADsAVwByAGkAdABlAC0ASABvAHMAdAAgACcAPQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9AD0APQA9ACcAOwBXAHIAaQB0AGUALQBIAG8AcwB0ACAAJwAnADsAVwByAGkAdABlAC0ASABvAHMAdAAgACcATwBwAGUAbgBpAG4AZwAgAGIAcgBvAHcAcwBlAHIALgAuAC4AJwA7AFMAdABhAHIAdAAtAFAAcgBvAGMAZQBzAHMAIAAkAHQALgBwAHUAYgBsAGkAYwBfAHUAcgBsAH0AZQBsAHMAZQB7AFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAnAFsAIQBdACAATgBvACAAdAB1AG4AbgBlAGwAIABmAG8AdQBuAGQAJwB9AH0AYwBhAHQAYwBoAHsAVwByAGkAdABlAC0ASABvAHMAdAAgACcAWwAhAF0AIABDAGEAbgBuAG8AdAAgAGMAbwBuAG4AZQBjAHQAIAB0AG8AIABjAHAAbwBsAGEAcgAnAH0A
echo.
pause
